import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Katie Schultz Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen flex flex-col">
          <header className="w-full justify-between flex p-2">
            <Link href="/">
              <div className="flex justify-end items-center">
                <div className="h-6 w-6 rounded-full bg-my-teal pr-4"></div>
                <h2 className="px-2 text-lg font-semibold">Katie Schultz</h2>
                <p>React Developer</p>
              </div>
            </Link>
            <div>
              <ul className="flex">
                <li className="border-r border-slate-800 px-2">
                  <Link href="/resume">Resume</Link>
                </li>
                <li className="border-r border-slate-800 px-2">
                  <Link href="/contact">Contact</Link>
                </li>
                <li className="px-2">
                  <Link href="/projects">Projects</Link>
                </li>
              </ul>
            </div>
          </header>
          <div className="p-2 flex h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
